I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 985, in script
    $ equip_item("body", "Type 07")
  File "game/script.rpy", line 985, in <module>
    $ equip_item("body", "Type 07")
  File "game/script.rpy", line 835, in equip_item
    modify_cleanliness(left_arm, -1)
NameError: name 'left_arm' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 985, in script
    $ equip_item("body", "Type 07")
  File "D:\renpy\renpy-8.0.1-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy\renpy-8.0.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 985, in <module>
    $ equip_item("body", "Type 07")
  File "game/script.rpy", line 835, in equip_item
    modify_cleanliness(left_arm, -1)
NameError: name 'left_arm' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
The Merge 1.0
Sat Oct 19 11:43:36 2024
