I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 71, in script
    init python:
  File "game/script.rpy", line 278, in <module>
    initialize_stats()
  File "game/script.rpy", line 274, in initialize_stats
    stats[stat]["current_strength"] = calculate_stat_value(stats[stat]["level"])
NameError: name 'calculate_stat_value' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 71, in script
    init python:
  File "D:\renpy\renpy-8.0.1-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy\renpy-8.0.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 278, in <module>
    initialize_stats()
  File "game/script.rpy", line 274, in initialize_stats
    stats[stat]["current_strength"] = calculate_stat_value(stats[stat]["level"])
NameError: name 'calculate_stat_value' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
The Merge 1.0
Sat Oct 12 00:14:40 2024
